export const textFiles = [
  { label: "Caesar Gallic Wars Book 1", value: "caesar_gall1.txt", translation: "urn:cts:latinLit:phi0448.phi001.perseus-eng2:1" },
  { label: "Caesar Gallic Wars Book 2", value: "caesar_gall2.txt", translation: "urn:cts:latinLit:phi0448.phi001.perseus-eng2:2" },
  { label: "Caesar Gallic Wars Book 3", value: "caesar_gall3.txt", translation: "urn:cts:latinLit:phi0448.phi001.perseus-eng2:3" },
  { label: "Caesar Gallic Wars Book 4", value: "caesar_gall4.txt", translation: "urn:cts:latinLit:phi0448.phi001.perseus-eng2:4" },
  { label: "Caesar Gallic Wars Book 5", value: "caesar_gall5.txt", translation: "urn:cts:latinLit:phi0448.phi001.perseus-eng2:5" },
  { label: "Caesar Gallic Wars Book 6", value: "caesar_gall6.txt", translation: "urn:cts:latinLit:phi0448.phi001.perseus-eng2:6" },
  { label: "Caesar Gallic Wars Book 7", value: "caesar_gall7.txt", translation: "urn:cts:latinLit:phi0448.phi001.perseus-eng2:7" },
  { label: "Caesar Gallic Wars Book 8", value: "caesar_gall8.txt", translation: "urn:cts:latinLit:phi0448.phi001.perseus-eng2:8" },
  { label: "Caesar Civil Wars Book 1", value: "caesar_bc1.txt", translation: "urn:cts:latinLit:phi0448.phi002.perseus-eng2:1" },
  { label: "Caesar Civil Wars Book 2", value: "caesar_bc2.txt", translation: "urn:cts:latinLit:phi0448.phi002.perseus-eng2:2" },
  { label: "Caesar Civil Wars Book 3", value: "caesar_bc3.txt", translation: "urn:cts:latinLit:phi0448.phi002.perseus-eng2:3" },
  { label: "Catullus", value: "catullus.txt", translation: "urn:cts:latinLit:phi0472.phi001.perseus-eng4:" },
  { label: "Cicero In Catilinam 1", value: "cicero_cat1.txt", translation: "urn:cts:latinLit:phi0474.phi013.perseus-eng2:1" },
  { label: "Cicero In Catilinam 2", value: "cicero_cat2.txt", translation: "urn:cts:latinLit:phi0474.phi013.perseus-eng2:2" },
  { label: "Cicero In Catilinam 3", value: "cicero_cat3.txt", translation: "urn:cts:latinLit:phi0474.phi013.perseus-eng2:3" },
  { label: "Cicero In Catilinam 4", value: "cicero_cat4.txt", translation: "urn:cts:latinLit:phi0474.phi013.perseus-eng2:4" },
  { label: "Cicero Pro Caelio", value: "cicero_cael.txt", translation: "urn:cts:latinLit:phi0474.phi024.perseus-eng1:" },
  { label: "Lucan Pharsalia Book 1", value: "lucan_lucan1.txt", translation: "urn:cts:latinLit:phi0917.phi001.perseus-eng1:1" },
  { label: "Lucan Pharsalia Book 2", value: "lucan_lucan2.txt", translation: "urn:cts:latinLit:phi0917.phi001.perseus-eng1:2" },
  { label: "Lucan Pharsalia Book 3", value: "lucan_lucan3.txt", translation: "urn:cts:latinLit:phi0917.phi001.perseus-eng1:3" },
  { label: "Lucan Pharsalia Book 4", value: "lucan_lucan4.txt", translation: "urn:cts:latinLit:phi0917.phi001.perseus-eng1:4" },
  { label: "Lucan Pharsalia Book 5", value: "lucan_lucan5.txt", translation: "urn:cts:latinLit:phi0917.phi001.perseus-eng1:5" },
  { label: "Lucan Pharsalia Book 6", value: "lucan_lucan6.txt", translation: "urn:cts:latinLit:phi0917.phi001.perseus-eng1:6" },
  { label: "Lucan Pharsalia Book 7", value: "lucan_lucan7.txt", translation: "urn:cts:latinLit:phi0917.phi001.perseus-eng1:7" },
  { label: "Lucan Pharsalia Book 8", value: "lucan_lucan8.txt", translation: "urn:cts:latinLit:phi0917.phi001.perseus-eng1:8" },
  { label: "Lucan Pharsalia Book 9", value: "lucan_lucan9.txt", translation: "urn:cts:latinLit:phi0917.phi001.perseus-eng1:9" },
  { label: "Lucan Pharsalia Book 10", value: "lucan_lucan10.txt", translation: "urn:cts:latinLit:phi0917.phi001.perseus-eng1:10" },
  { label: "Lucretius De Rerum Natura Book 1", value: "lucretius_lucretius1.txt", translation: "urn:cts:latinLit:phi0550.phi001.perseus-eng1:1" },
  { label: "Lucretius De Rerum Natura Book 2", value: "lucretius_lucretius2.txt", translation: "urn:cts:latinLit:phi0550.phi001.perseus-eng1:2" },
  { label: "Lucretius De Rerum Natura Book 3", value: "lucretius_lucretius3.txt", translation: "urn:cts:latinLit:phi0550.phi001.perseus-eng1:3" },
  { label: "Lucretius De Rerum Natura Book 4", value: "lucretius_lucretius4.txt", translation: "urn:cts:latinLit:phi0550.phi001.perseus-eng1:4" },
  { label: "Lucretius De Rerum Natura Book 5", value: "lucretius_lucretius5.txt", translation: "urn:cts:latinLit:phi0550.phi001.perseus-eng1:5" },
  { label: "Lucretius De Rerum Natura Book 6", value: "lucretius_lucretius6.txt", translation: "urn:cts:latinLit:phi0550.phi001.perseus-eng1:6" },
  { label: "Ovid Amores Book 1", value: "ovid_ovid.amor1.txt", translation: "urn:cts:latinLit:phi0959.phi001.perseus-eng2:1" },
  { label: "Ovid Amores Book 2", value: "ovid_ovid.amor2.txt", translation: "urn:cts:latinLit:phi0959.phi001.perseus-eng2:2" },
  { label: "Ovid Amores Book 3", value: "ovid_ovid.amor3.txt", translation: "urn:cts:latinLit:phi0959.phi001.perseus-eng2:3" },
  { label: "Ovid Heroides 1 - Penelope to Ulysses", value: "ovid_ovid.her1.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:1"},
  { label: "Ovid Heroides 2 - Phyllis to Demophoon", value: "ovid_ovid.her2.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:2"},
  { label: "Ovid Heroides 3 - Briseis to Achilles", value: "ovid_ovid.her3.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:3"},
  { label: "Ovid Heroides 4 - Phaedra to Hippolytus", value: "ovid_ovid.her4.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:4"},
  { label: "Ovid Heroides 5 - Oenone to Paris", value: "ovid_ovid.her5.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:5"},
  { label: "Ovid Heroides 6 - Hypsipyle to Jason", value: "ovid_ovid.her6.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:6"},
  { label: "Ovid Heroides 7 - Dido to Aeneas", value: "ovid_ovid.her7.txt", translation: "filler"},
  { label: "Ovid Heroides 8 - Hermione to Orestes", value: "ovid_ovid.her8.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:8"},
  { label: "Ovid Heroides 9 - Deianira to Hercules", value: "ovid_ovid.her9.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:9"},
  { label: "Ovid Heroides 10 - Ariadne to Theseus", value: "ovid_ovid.her10.txt", translation: "filler"},
  { label: "Ovid Heroides 11 - Canace to Macareus", value: "ovid_ovid.her11.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:11"},
  { label: "Ovid Heroides 12 - Medea to Jason", value: "ovid_ovid.her12.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:12"},
  { label: "Ovid Heroides 13 - Laodamia to Protesilaus", value: "ovid_ovid.her13.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:13"},
  { label: "Ovid Heroides 14 - Hypermnestra to Lynceus", value: "ovid_ovid.her14.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:14"},
  { label: "Ovid Heroides 15 - Sappho to Phaon", value: "ovid_ovid.her15.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:15"},
  { label: "Ovid Heroides 16 - Paris to Helen", value: "ovid_ovid.her16.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:16"},
  { label: "Ovid Heroides 17 - Helen to Paris", value: "ovid_ovid.her17.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:17"},
  { label: "Ovid Heroides 18 - Leander to Hero", value: "ovid_ovid.her18.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:18"},
  { label: "Ovid Heroides 19 - Hero to Leander", value: "ovid_ovid.her19.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:19"},
  { label: "Ovid Heroides 20 - Acontius to Cydippe", value: "ovid_ovid.her20.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:20"},
  { label: "Ovid Heroides 21 - Cydippe to Acontius", value: "ovid_ovid.her21.txt", translation: "urn:cts:latinLit:phi0959.phi002.perseus-eng2:21"},
  { label: "Ovid Ars Amatoria Book 1", value: "ovid_ovid.artis1.txt", translation: "urn:cts:latinLit:phi0959.phi004.perseus-eng2:1"},
  { label: "Ovid Ars Amatoria Book 2", value: "ovid_ovid.artis2.txt", translation: "urn:cts:latinLit:phi0959.phi004.perseus-eng2:2"},
  { label: "Ovid Ars Amatoria Book 3", value: "ovid_ovid.artis3.txt", translation: "urn:cts:latinLit:phi0959.phi004.perseus-eng2:3"},
  { label: "Ovid Metamorphoses Book 1", value: "ovid_ovid.met1.txt", translation: "urn:cts:latinLit:phi0959.phi006.perseus-eng3:1"},
  { label: "Ovid Metamorphoses Book 2", value: "ovid_ovid.met2.txt", translation: "urn:cts:latinLit:phi0959.phi006.perseus-eng3:2"},
  { label: "Ovid Metamorphoses Book 3", value: "ovid_ovid.met3.txt", translation: "urn:cts:latinLit:phi0959.phi006.perseus-eng3:3"},
  { label: "Ovid Metamorphoses Book 4", value: "ovid_ovid.met4.txt", translation: "urn:cts:latinLit:phi0959.phi006.perseus-eng3:4"},
  { label: "Ovid Metamorphoses Book 5", value: "ovid_ovid.met5.txt", translation: "urn:cts:latinLit:phi0959.phi006.perseus-eng3:5"},
  { label: "Ovid Metamorphoses Book 6", value: "ovid_ovid.met6.txt", translation: "urn:cts:latinLit:phi0959.phi006.perseus-eng3:6"},
  { label: "Ovid Metamorphoses Book 7", value: "ovid_ovid.met7.txt", translation: "urn:cts:latinLit:phi0959.phi006.perseus-eng3:7"},
  { label: "Ovid Metamorphoses Book 8", value: "ovid_ovid.met8.txt", translation: "urn:cts:latinLit:phi0959.phi006.perseus-eng3:8"},
  { label: "Ovid Metamorphoses Book 9", value: "ovid_ovid.met9.txt", translation: "urn:cts:latinLit:phi0959.phi006.perseus-eng3:9"},
  { label: "Ovid Metamorphoses Book 10", value: "ovid_ovid.met10.txt", translation: "urn:cts:latinLit:phi0959.phi006.perseus-eng3:10"},
  { label: "Ovid Metamorphoses Book 11", value: "ovid_ovid.met11.txt", translation: "urn:cts:latinLit:phi0959.phi006.perseus-eng3:11"},
  { label: "Ovid Metamorphoses Book 12", value: "ovid_ovid.met12.txt", translation: "urn:cts:latinLit:phi0959.phi006.perseus-eng3:12"},
  { label: "Ovid Metamorphoses Book 13", value: "ovid_ovid.met13.txt", translation: "urn:cts:latinLit:phi0959.phi006.perseus-eng3:13"},
  { label: "Ovid Metamorphoses Book 14", value: "ovid_ovid.met14.txt", translation: "urn:cts:latinLit:phi0959.phi006.perseus-eng3:14"},
  { label: "Ovid Metamorphoses Book 15", value: "ovid_ovid.met15.txt", translation: "urn:cts:latinLit:phi0959.phi006.perseus-eng3:15"},
  { label: "Sallust Catilinae Coniuratio", value: "sall.1.txt", translation: "urn:cts:latinLit:phi0631.phi001.perseus-eng2:"},
  { label: "Vergil Aeneid Book 1", value: "vergil_aen1.txt", translation: "urn:cts:latinLit:phi0690.phi003.perseus-eng2:1" },
  { label: "Vergil Aeneid Book 2", value: "vergil_aen2.txt", translation: "urn:cts:latinLit:phi0690.phi003.perseus-eng2:2" },
  { label: "Vergil Aeneid Book 3", value: "vergil_aen3.txt", translation: "urn:cts:latinLit:phi0690.phi003.perseus-eng2:3" },
  { label: "Vergil Aeneid Book 4", value: "vergil_aen4.txt", translation: "urn:cts:latinLit:phi0690.phi003.perseus-eng2:4" },
  { label: "Vergil Aeneid Book 5", value: "vergil_aen5.txt", translation: "urn:cts:latinLit:phi0690.phi003.perseus-eng2:5" },
  { label: "Vergil Aeneid Book 6", value: "vergil_aen6.txt", translation: "urn:cts:latinLit:phi0690.phi003.perseus-eng2:6" },
  { label: "Vergil Aeneid Book 7", value: "vergil_aen7.txt", translation: "urn:cts:latinLit:phi0690.phi003.perseus-eng2:7" },
  { label: "Vergil Aeneid Book 8", value: "vergil_aen8.txt", translation: "urn:cts:latinLit:phi0690.phi003.perseus-eng2:8" },
  { label: "Vergil Aeneid Book 9", value: "vergil_aen9.txt", translation: "urn:cts:latinLit:phi0690.phi003.perseus-eng2:9" },
  { label: "Vergil Aeneid Book 10", value: "vergil_aen10.txt", translation: "urn:cts:latinLit:phi0690.phi003.perseus-eng2:10" },
  { label: "Vergil Aeneid Book 11", value: "vergil_aen11.txt", translation: "urn:cts:latinLit:phi0690.phi003.perseus-eng2:11" },
  { label: "Vergil Aeneid Book 12", value: "vergil_aen12.txt", translation: "urn:cts:latinLit:phi0690.phi003.perseus-eng2:12" },
  { label: "Vergil Eclogue 1", value: "vergil_ec1.txt", translation: "urn:cts:latinLit:phi0690.phi001.perseus-eng2:1" },
  { label: "Vergil Eclogue 2", value: "vergil_ec2.txt", translation: "urn:cts:latinLit:phi0690.phi001.perseus-eng2:2" },
  { label: "Vergil Eclogue 3", value: "vergil_ec3.txt", translation: "urn:cts:latinLit:phi0690.phi001.perseus-eng2:3" },
  { label: "Vergil Eclogue 4", value: "vergil_ec4.txt", translation: "urn:cts:latinLit:phi0690.phi001.perseus-eng2:4" },
  { label: "Vergil Eclogue 5", value: "vergil_ec5.txt", translation: "urn:cts:latinLit:phi0690.phi001.perseus-eng2:5" },
  { label: "Vergil Eclogue 6", value: "vergil_ec6.txt", translation: "urn:cts:latinLit:phi0690.phi001.perseus-eng2:6" },
  { label: "Vergil Eclogue 7", value: "vergil_ec7.txt", translation: "urn:cts:latinLit:phi0690.phi001.perseus-eng2:7" },
  { label: "Vergil Eclogue 8", value: "vergil_ec8.txt", translation: "urn:cts:latinLit:phi0690.phi001.perseus-eng2:8" },
  { label: "Vergil Eclogue 9", value: "vergil_ec9.txt", translation: "urn:cts:latinLit:phi0690.phi001.perseus-eng2:9" },
  { label: "Vergil Eclogue 10", value: "vergil_ec10.txt", translation: "urn:cts:latinLit:phi0690.phi001.perseus-eng2:10" },
  { label: "Vergil Georgics Book 1", value: "vergil_geo1.txt", translation: "urn:cts:latinLit:phi0690.phi002.perseus-eng2:1" },
  { label: "Vergil Georgics Book 2", value: "vergil_geo2.txt", translation: "urn:cts:latinLit:phi0690.phi002.perseus-eng2:2" },
  { label: "Vergil Georgics Book 3", value: "vergil_geo3.txt", translation: "urn:cts:latinLit:phi0690.phi002.perseus-eng2:3" },
  { label: "Vergil Georgics Book 4", value: "vergil_geo4.txt", translation: "urn:cts:latinLit:phi0690.phi002.perseus-eng2:4" },
];
